services:
  ros2-jazzy:
    build:
      context: ..
      dockerfile: locali/Dockerfile

    image: ros2-jazzy-robot-localization
    container_name: ros2-jazzy-robot-localization

    stdin_open: true
    tty: true

    working_dir: /ros2_ws

    volumes:
      - ../src:/ros2_ws/src
      - ../bags:/ros2_ws/bags
      - ../config:/ros2_ws/config

    environment:
      ROS_DOMAIN_ID: 0
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp

    network_mode: host
    ipc: host

    command: bash
